"""
    Author: Aleksa Boricic 2020/0294
    Automatically generated by Django
"""

from django.apps import AppConfig

class AleksaConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'producerApp'
