# Generated by Django 4.2.1 on 2023-05-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='korisnik',
            name='username',
        ),
        migrations.AlterField(
            model_name='korisnik',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
