# Generated by Django 4.2 on 2023-05-31 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pretplacen',
            name='id',
        ),
        migrations.AddField(
            model_name='pretplacen',
            name='idpretplacen',
            field=models.AutoField(db_column='idPretplacen', default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pretplacen',
            name='idkorisnik',
            field=models.ForeignKey(db_column='idKorisnik', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='slika',
            name='slika',
            field=models.ImageField(default=None, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='somelijer',
            name='slika',
            field=models.ImageField(default=None, null=True, upload_to='images'),
        ),
    ]
