# Generated by Django 4.2 on 2023-05-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnik',
            name='adresa',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='korisnik',
            name='javnoime',
            field=models.CharField(blank=True, db_column='javnoIme', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pretplata',
            name='naslov',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='proizvodjac',
            name='imefirme',
            field=models.CharField(blank=True, db_column='imeFirme', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='somelijer',
            name='ime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='upitnikodgovor',
            name='odgovor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='upitnikpitanje',
            name='tekst',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vino',
            name='naziv',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vrstaobilaska',
            name='naziv',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
