# Generated by Django 4.2.1 on 2023-05-30 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ukorpi',
            name='kolicina',
            field=models.IntegerField(blank=True, db_column='kolicina', null=True),
        ),
    ]
