# Generated by Django 4.2.1 on 2023-05-24 14:06

from django.db import migrations
import userApp.manager


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0002_remove_korisnik_username_alter_korisnik_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='korisnik',
            managers=[
                ('objects', userApp.manager.KorisnikManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='kupac',
            managers=[
                ('objects', userApp.manager.KorisnikManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='proizvodjac',
            managers=[
                ('objects', userApp.manager.KorisnikManager()),
            ],
        ),
    ]
