# Generated by Django 4.2 on 2023-05-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0002_alter_korisnik_adresa_alter_korisnik_javnoime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponuda',
            name='idponuda',
            field=models.AutoField(db_column='idPonuda', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pretplata',
            name='idpretplata',
            field=models.AutoField(db_column='idPretplata', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recenzija',
            name='idrecenzija',
            field=models.AutoField(db_column='idRecenzija', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='slika',
            name='idslika',
            field=models.AutoField(db_column='idSlika', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='somelijer',
            name='idsomelijer',
            field=models.AutoField(db_column='idSomelijer', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='idtag',
            field=models.AutoField(db_column='idTag', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='termin',
            name='idtermin',
            field=models.AutoField(db_column='idTermin', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ukorpi',
            name='idkorpa',
            field=models.AutoField(db_column='idKorpa', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='upitnikodgovor',
            name='idodgovor',
            field=models.AutoField(db_column='idOdgovor', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='upitnikpitanje',
            name='idpitanje',
            field=models.AutoField(db_column='idPitanje', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vrstaobilaska',
            name='idobilazak',
            field=models.AutoField(db_column='idObilazak', primary_key=True, serialize=False),
        ),
    ]
