# Generated by Django 4.2.1 on 2023-05-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0003_alter_korisnik_managers_alter_kupac_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proizvodjac',
            name='logo',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
