# Generated by Django 4.2.1 on 2023-05-24 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0004_proizvodjac_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proizvodjac',
            name='logo',
        ),
    ]
