# Generated by Django 4.2.1 on 2023-06-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0005_alter_termin_vreme'),
    ]

    operations = [
        migrations.AddField(
            model_name='termin',
            name='brojljudi',
            field=models.IntegerField(blank=True, db_column='brojLjudi', null=True),
        ),
    ]
