# Generated by Django 4.2.1 on 2023-06-03 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0006_termin_brojljudi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezultatupitnika',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rezultatupitnika',
            name='idkorisnik',
            field=models.ForeignKey(db_column='idKorisnik', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
