# Generated by Django 4.2.1 on 2023-06-19 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0008_alter_rezultatupitnika_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pretplacen',
            unique_together=set(),
        ),
    ]
